from pydantic import BaseModel
from typing import Optional


class JobDescriptionContent(BaseModel):
    about_company: Optional[str] = ...
    about_role: Optional[str] = ...
    requirements: Optional[str] = ...
    nice_to_have: Optional[str] = ...
    responsibilities: Optional[str] = ...
    other: Optional[str] = ...

class JobDescriptionFields(BaseModel):
    job_title: str
    job_description: JobDescriptionContent
